### ISSUE TITLE
What if no npm?

### ISSUE THREAD

**Issue by GregJohnStewart** [petya0927/real-dark-mode#4]
Hey! Love this cheesy effect. However, I don't use npm on my website. I feel like this should be doable on core js, or maybe even in css alone.

Thoughts?

**Comment by petya0927** [comment]
Hi!

Thanks for the question! You're absolutely right, it's so much easier to do it in plain js+css without any packagemanager, or typescript. Actually it's my first package and I did it only for the sake of practice and just to try it out.

Do you think I should open a new repo for plain js implementation? Or do you have something in mind?

**Comment by GregJohnStewart** [comment]
I think it makes sense to stay in one repo, just making the plain js and/or css available in the repo and point to it in the readme would be enough!

**Comment by GregJohnStewart** [comment]
@petya0927 Close enough! At least for me to finalize it a little. Functionally, the only thing I really changed was the parameter for `realDarkMode`, as plain js didn't like it before. Otherwise, I wrapped it in an object for a simple form of namespace.

In PR #5 for your review :)
