### ISSUE TITLE
how do you use it

### ISSUE THREAD

**Issue by epicman38** [petya0927/real-dark-mode#6]
i was looking around and could not find a way to enable it

**Comment by petya0927** [comment]
Hi! Can you please elaborate on that? What do you mean how to enable it?

**Comment by epicman38** [comment]
like using it where would I insert the code? Is it for personal websites only?

**Comment by petya0927** [comment]
Okay, so this is an npm package, here's how you can get started with node.js and npm: https://docs.npmjs.com/downloading-and-installing-node-js-and-npm

After you installed npm and initialised an npm project, you can consult the readme.md documentation to get started. 

Or if you can't / don't want to use npm, we created a plain-js implementation, which you can just download and use as a script in your website.
